File copied : /root/sailfish/code/static_analysis/analysis/EAI_TokenERC.sol
processing /root/sailfish/code/static_analysis/analysis/EAI_TokenERC.sol
Installing solc '0.4.26'...
Version '0.4.26' installed.
Switched global version to 0.4.26
[INFO] | 2023-12-05 03:53:50 AM | analyzer.EAI_TokenERC | Analysis started at: 2023-12-05 03:53:50 AM
[INFO] | 2023-12-05 03:53:51 AM | analyzer.EAI_TokenERC | Version constraints: ['^0.4.16']
[INFO] | 2023-12-05 03:53:51 AM | analyzer.EAI_TokenERC | solc version: v0.4.16
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/platform/solc.py", line 368, in _run_solc
    ret = json.loads(stdout)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.8-py3.6.egg/slither/slither.py", line 60, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/crytic_compile.py", line 137, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/crytic_compile.py", line 987, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/platform/solc.py", line 152, in compile
    force_legacy_json=force_legacy_json,
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/platform/solc.py", line 372, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation /root/sailfish/code/static_analysis/analysis/EAI_TokenERC.sol:56:22: Error: Expected token Semicolon got 'LParen'
        emit Transfer(_from, _to, _value);
                     ^
EAI_TokenERC.sol:56:22: Error: Expected token Semicolon got 'LParen'
        emit Transfer(_from, _to, _value);
                     ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "contractlint.py", line 67, in analyze_contracts
    slither_obj = Slither(contract_path, solc=solc_path)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.8-py3.6.egg/slither/slither.py", line 63, in __init__
    raise SlitherError('Invalid compilation: \n'+str(e))
slither.exceptions.SlitherError: Invalid compilation: 
Invalid solc compilation /root/sailfish/code/static_analysis/analysis/EAI_TokenERC.sol:56:22: Error: Expected token Semicolon got 'LParen'
        emit Transfer(_from, _to, _value);
                     ^
EAI_TokenERC.sol:56:22: Error: Expected token Semicolon got 'LParen'
        emit Transfer(_from, _to, _value);
                     ^

[36m[#] Analysing started: EAI_TokenERC.sol[0m
/root/.solc-select/artifacts/solc-0.4.26
21cca4128d9992088d30c18977b891e8bf6841b2609d700b368dc503a6d7a183
